import 'package:photo_editing_app/model/filterApiResModel.dart';

class Filters {
  List<Filter> list() {
    return <Filter>[
      Filter(
        filterName: 'No Filter',
        matrix: [
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
        ],
      ),
      Filter(
        filterName: 'Purple',
        matrix: [
          1,
          -0.2,
          0,
          0,
          0,
          0,
          1,
          0,
          -0.1,
          0,
          0,
          1.2,
          1,
          0.1,
          0,
          0,
          0,
          1.7,
          1,
          0,
        ],
      ),
      Filter(
        filterName: 'Cyan',
        matrix: [
          1,
          0,
          0,
          1.9,
          -2.2,
          0,
          1,
          0,
          0.0,
          0.3,
          0,
          0,
          1,
          0,
          0.5,
          0,
          0,
          0,
          1,
          0.2,
        ],
      ),
      Filter(
        filterName: 'Black & White',
        matrix: [
          0,
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          1,
          0,
        ],
      ),
      Filter(
        filterName: 'Yellow',
        matrix: [
          1,
          0,
          0,
          0,
          0,
          -0.2,
          1.0,
          0.3,
          0.1,
          0,
          -0.1,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          0,
        ],
      ),
      Filter(
        filterName: 'Vintage',
        matrix: [
          0.9,
          0.5,
          0.1,
          0.0,
          0.0,
          0.3,
          0.8,
          0.1,
          0.0,
          0.0,
          0.2,
          0.3,
          0.5,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          1.0,
          0.0
        ],
      ),
      Filter(
        filterName: 'Greyscale',
        matrix: [
          0.2126,
          0.7152,
          0.0722,
          0.0,
          0.0,
          0.2126,
          0.7152,
          0.0722,
          0.0,
          0.0,
          0.2126,
          0.7152,
          0.0722,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          1.0,
          0.0
        ],
      ),
      Filter(
        filterName: 'Sepia',
        matrix: [
          0.39,
          0.769,
          0.189,
          0.0,
          0.0,
          0.349,
          0.686,
          0.168,
          0.0,
          0.0,
          0.272,
          0.534,
          0.131,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          1.0,
          0.0
        ],
      ),
    ];
  }
}
